# Generated by Django 4.1.5 on 2023-01-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Company_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('About', models.TextField()),
                ('Type', models.CharField(choices=[('IT', 'IT'), ('Non Tech', 'Non Tech'), ('Mobiles', 'Mobiles')], max_length=100)),
                ('addedDate', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
