# Generated by Django 4.1.5 on 2023-01-18 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Empoyee_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Employee_type', models.CharField(choices=[('Developer', 'Developer'), ('Manager', 'Manager'), ('Supervisor', 'Supervisor')], max_length=100)),
                ('Company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
